name: biologger-sim
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - scipy
  - pyzmq
  - pydantic
  - pyyaml
  - ruff
  - mypy
  - types-PyYAML
  - pre-commit
  - pytest
  - pip
  - pip:
    - -e .
