name: biologger-sim
channels:
  - conda-forge
  - nodefaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - pyarrow
  - scipy
  - pyzmq
  - pydantic
  - msgpack
  - pyyaml
  - ruff
  - mypy
  - types-PyYAML
  - pandas-stubs
  - pre-commit
  - pytest
  - sphinx
  - sphinx_rtd_theme
  - pip
  - pip:
      - warp-lang
