mode: SIMULATION
simulation:
  playback_speed: 1.0
  loop: true
  meta_file: ../datasets/biologger_meta.csv
  entities:
    - sim_id: sword_ahrs
      tag_id: RED001_20220812
      sampling_rate_hz: 16.0
      clock_source: fixed_frequency
      input_file: ../datasets/Swordfish-RED001_20220812_19A0564/RED001_20220812_19A0564.csv
      calibration:
        locked_attachment_roll_deg: 117.428765982488
        locked_attachment_pitch_deg: -5.98660533732103
        locked_mag_offset_x: -21.150280479634
        locked_mag_offset_y: -12.8881473919571
        locked_mag_offset_z: 30.270469350479
        locked_mag_sphere_radius: 56.5142398578007
      depth_estimation:
        algorithm: causal_sample_hold
      ahrs:
        enabled: false
        algorithm: madgwick
        beta: 0.033
        use_adaptive: true
        normal_gravity_threshold: 0.05
        slip_gravity_threshold: 0.15
        smoothing_alpha: 0.01
  zmq:
    port: 5555
    host: "0.0.0.0"
