mode: SIMULATION

calibration:
  attachment_angle_mode: fixed
  magnetometer_mode: fixed
  # Values copied from biologger-pseudotrack/config_swordfish_postfacto_locked_params.yml
  locked_attachment_roll_deg: 117.428765982488
  locked_attachment_pitch_deg: -5.98660533732103
  locked_mag_offset_x: -21.150280479634
  locked_mag_offset_y: -12.8881473919571
  locked_mag_offset_z: 30.270469350479
  locked_mag_sphere_radius: 56.5142398578007

depth:
  mode: realtime

ahrs:
  enabled: false

simulation:
  input_file: ../datasets/Swordfish-RED001_20220812_19A0564/RED001_20220812_19A0564.csv
  rate_hz: 16.0
  loop: true
  zmq:
    port: 5555
    host: "127.0.0.1"
