mode: SIMULATION
simulation:
  playback_speed: 1.0
  loop: true
  meta_file: ../datasets/biologger_meta.csv
  entities:
    - sim_id: sword_causal
      tag_id: RED001
      sampling_rate_hz: 16.0
      input_file: ../datasets/Swordfish-RED001_20220812_19A0564/RED001_20220812_19A0564.csv
      calibration:
        # Values copied from biologger-pseudotrack/config_swordfish_postfacto_locked_params.yml
        locked_attachment_roll_deg: 117.428765982488
        locked_attachment_pitch_deg: -5.98660533732103
        locked_mag_offset_x: -21.150280479634
        locked_mag_offset_y: -12.8881473919571
        locked_mag_offset_z: 30.270469350479
        locked_mag_sphere_radius: 56.5142398578007
      depth:
        enabled: true
      ahrs:
        enabled: false
  zmq:
    port: 5555
    host: "0.0.0.0"
