mode: LAB

calibration:
  attachment_angle_mode: batch_compute
  magnetometer_mode: batch_compute

depth:
  mode: interpolate

simulation:
  input_file: ../datasets/Swordfish-RED001_20220812_19A0564/RED001_20220812_19A0564.csv
  rate_hz: 16.0
  loop: true
  zmq:
    port: 5555
    host: "127.0.0.1"
